name: noa
on: pull_request

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.15.1
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15.1

            - name: Check out code into the Go module directory
              uses: actions/checkout@v1

            - name: Get dependencies
              run: go get -v -t -d ./...

            - name: cp testdata
              run: cp checkmsg/testdata/testExclusion1.txt ./ngwords.txt

            - name: Test code
              run: go test -v ./...
